Ferlab-Ste-Justine/clin-ui

.github/workflows/build.yml
.github/workflows/commit_lint.yml
.github/workflows/publish_image_sha.yml
Dockerfile
env-qa
static.conf

Implemented docker image and related workflows

feat: CLIN-446 Implemented docker image and related workflows

---

.github/workflows/publish_image_sha.yml

Fixed publication pipeline trigger branch

fix: CLIN-446 Fixed publication pipeline trigger branch

---

env-qa

Changed arranger for the clin one

fix: CLIN-446 Changed arranger for the clin one

---

src/components/Layout/Content/Header.module.scss
src/components/Layout/Content/Header.tsx
src/components/Layout/Header/LangMenu/index.tsx
src/store/graphql/prescriptions/actions.tsx
src/store/graphql/prescriptions/models/Prescription.ts
src/style/themes/clin/_layout.scss
src/views/screens/search/PatientsPrescriptions.tsx
src/views/screens/search/table/cell/PatientId.tsx
src/views/screens/search/table/patientsColumns.tsx
src/views/screens/search/table/prescriptionColumns.tsx

fix: #CLIN-500 add padding in content header, add patientId cell link

---

src/style/themes/clin/_layout.scss
src/views/screens/search/ContentContainer.module.scss
src/views/screens/search/ContentContainer.tsx
src/views/screens/search/PatientsPrescriptions.tsx
src/views/screens/search/table/table.module.scss

fix: #clin-511 update table content style

---

src/style/themes/clin/antd-clin-theme.less
src/style/themes/clin/antd/tabs.less
src/style/themes/clin/dist/antd.css
src/views/screens/search/ContentContainer.module.scss
src/views/screens/search/ContentContainer.tsx
src/views/screens/search/table/table.module.scss
src/views/screens/variant/VariantPageContainer.module.scss

mise a jour du style des tabs de type 'card' pour le default antd.
mise a jour de la recherche et variant

fix global ant tabs type cards, update variant and search

---

src/views/screens/search/table/Table.tsx

- Mise a jour de la pagination

Clin 527 update pagination to adopt small variant

---

src/style/themes/clin/antd/collapse.less
src/style/themes/clin/dist/antd.css
src/views/screens/search/ContentContainer.module.scss
src/views/screens/search/ContentHeader.scss
src/views/screens/search/PatientsPrescriptions.module.scss
src/views/screens/search/PatientsPrescriptions.tsx
src/views/screens/search/Sidebar.module.scss

CLIN-511: fix patient presc layout

---

src/style/themes/clin/antd-clin-theme.less
src/style/themes/clin/antd/inputs.less
src/style/themes/clin/antd/selects.less
src/style/themes/clin/dist/antd.css
src/views/screens/search/ContentHeader.scss
src/views/screens/search/ContentHeader.tsx

CLIN-68: fix input focused state

---

src/style/themes/clin/antd/collapse.less
src/style/themes/clin/dist/antd.css
src/views/screens/search/table/Table.tsx
src/views/screens/search/table/cell/PatientId.tsx

Clin 511 fix layout

---

src/views/screens/search/PatientsPrescriptions.tsx
src/views/screens/search/Sidebar.module.scss
src/views/screens/search/Sidebar.tsx
src/views/screens/search/SidebarFilter.module.scss
src/views/screens/search/SidebarFilters.tsx

https://user-images.githubusercontent.com/28421005/144924091-05833443-6cba-4ade-956a-5229d1f1cd90.mov

CLIN-511: Add open transition on sider and loader

---

src/views/screens/search/ContentHeader.tsx

https://user-images.githubusercontent.com/28421005/145273463-44893543-1de4-433c-b1db-1bffc8140b43.mov

CLIN-542: fix autocomplete

---

env-qa

Update arranger project clin blue 2021 12 09 v1

---

env-qa
package-lock.json
package.json
src/locales/en.js
src/locales/fr.js
src/store/graphql/prescriptions/models/Prescription.ts
src/store/graphql/prescriptions/queries.tsx
src/style/themes/clin/colors.less
src/views/screens/search/table/prescriptionColumns.tsx

Clin 563 use correct status value

---

src/locales/en.js
src/locales/fr.js
src/store/graphql/utils/Filters.tsx
src/views/screens/search/ContentContainer.tsx
src/views/screens/search/table/prescriptionColumns.tsx

fix: clin-569 Add logic to support french translation

---

src/locales/en.js
src/locales/fr.js
src/style/themes/clin/colors.less
src/utils/date.ts
src/views/screens/search/table/patientsColumns.tsx
src/views/screens/search/table/prescriptionColumns.tsx

fix: clin-559 always use YYYY-MM-DD date format with tooltip

---

src/store/graphql/utils/Filters.tsx
src/views/screens/search/ContentContainer.tsx

Cache les filtres qui n'ont pas de valeur

Clin 577 hide empty filter

---

src/store/graphql/patients/models/Patient.ts
src/store/graphql/patients/queries.tsx

Fix the loading issues with the patients table

Clin 595 change in patients request fields

---

src/store/graphql/patients/queries.tsx
src/store/graphql/prescriptions/queries.tsx
src/views/screens/search/ContentContainer.tsx
src/views/screens/search/PatientsPrescriptions.tsx

Trier les tables par date de modification

fix: clin-602 sort search tables

---

src/auth/keycloak-api/manager.ts
src/locales/en.js
src/locales/fr.js
src/store/graphql/utils/Filters.tsx
src/store/graphql/variants/models.ts
src/store/graphql/variants/queries.tsx
src/views/screens/variant/VariantPageContainer.tsx
src/views/screens/variant/VariantSearchPage.tsx

CLIN-683: add gene panel to facet

---

package-lock.json
src/views/screens/search/table/columns.ts
src/views/screens/search/table/prescriptionColumns.tsx

Prévient un crash si le label est null.

fix: #clin-746 dont crash patients page on invalid status

---

src/views/screens/search/table/NanuqExportButton.tsx

Changement dans les champs du fichier json de nanuq

feat: CLIN-773 modifier champs nanuq

---

src/views/screens/variant/Entity/index.module.scss
src/views/screens/variant/Entity/index.tsx
src/views/screens/variant/VariantTableContainer.tsx

https://ferlab-crsj.atlassian.net/browse/CLIN-715

feat: CLIN-715 - add variant previous button

---

env-qa
env-staging

Changed domain for hospital cluster

feat: INFRA-6 Changed domain for hospital cluster

---

.github/workflows/quality.yml
src/App.test.js
src/utils/tests/utils.helper.spec.tsx

Ajout d'un github Action Quality
Ajout de tests unitaires pour utils/helper

feat: CLIN-835 Ajout du gitHub action Quality et des tests unitaires

---

package-lock.json
package.json
src/babel.config.js
src/components/Layout/Footer/tests/Footer.test.js
src/components/Layout/Footer/tests/__snapshots__/Footer.test.js.snap
src/components/Layout/Header/tests/Header.test.js

closes #CLIN-864
Mettre en place un setup pour faire des tests d’intégration SnapShot
Ajout de tests
- Footer
- Header (skip)

feat: CLIN-864 Setup de tests d'intégration SnapShot

---

src/locales/en.json
src/locales/fr.json
src/views/screens/variant/Entity/ResumePanel/Summary/index.tsx

Traduction de chromosome + ajout de " : "  a la fin des titre

fix: CLIN-815 ajustement informations sommaires

---

src/views/screens/variant/Entity/PatientPanel/index.tsx

Correction d'un proband oublié

fix: CLIN-887 traduire proband Patient

---

src/components/Layout/Header/index.tsx

feat: CLIN-608 add ref to patient search page

---

src/views/screens/variant/Entity/ResumePanel/index.tsx

Alignement des colonnes pour les tableau onglet résumé

fix: CLIN-821 alignement colonne Variant

---

env-qa
package-lock.json
src/graphql/variants/models.ts
src/style/themes/clin/dist/antd.css
src/views/screens/variant/Entity/ResumePanel/index.tsx

Convert refseq_mrna_id from String to Array
https://ferlab-crsj.atlassian.net/browse/CLIN-920
Can be tested with arranger project: clin_refseq_green
Example of result:

feat: CLIN-920 variant refseq array of ids

---

.github/workflows/publish_image_tag.yml
env-prod

Added prod image release workflow

feat: INFRA-7 Added prod image release workflow

---

src/locales/en.json
src/locales/fr.json
src/views/screens/search/table/patientsColumns.tsx

fix: CLIN-959 ajuste patient modif date title

---

src/locales/en.json
src/locales/fr.json
src/views/screens/variant/Entity/PatientPanel/index.tsx

fix: CLIN-886 add unknown filter for gender

---

package-lock.json
package.json

https://user-images.githubusercontent.com/28421005/165583430-8cbc125e-90b7-448e-8f8c-a9ee5bf4a5af.mov

fix: CLIN-859 update ferlab to fix range filter

---

src/views/screens/variant/Entity/SummaryPanel/Summary/index.tsx

https://ferlab-crsj.atlassian.net/browse/CLIN-985

fix: CLIN-985 variant patient tab

---

src/App.tsx

fix: CLIN-994 fix empty default message

---

src/graphql/utils/Filters.tsx
src/views/screens/variant/filters/CustomFilterContainer.tsx

fix: CLIN-948 fix for chromosome
